version: '3.8'

services:
  postgres:
    image: postgres
    container_name: 'e-cmmc-postgres'
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: e-cmmc
    volumes:
      - .\src\data\postgresql\init-db.sql:/docker-entrypoint.init-db.d/init-db.sql

  sqlite3:
    image: keinos/sqlite3
    working_dir: /workspaces
    container_name: 'e-cmmc-sqlite3'
    volumes:
      - .\src\data\sqlite3\init.sql:/workspaces/init.sql
      - .\src\data\sqlite3:/workspaces
    command: sh -c 'sqlite3 placement.db < /workspaces/init.sql && tail -f /dev/null'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'e-cmmc-rabbitmq'
    hostname: e-cmmc-brk
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  api-order:
    build:
      context: .\src\server\api-order\
      dockerfile: Dockerfile
    container_name: 'e-cmmc-api-order'
    ports:
      - 5001:5001
    depends_on:
      - sqlite3

  api-inventory:
    build:
      context: .\src\server\api-inventory\E.CMMC.Inventory
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005
    depends_on:
      - postgres
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: 'e-cmmc-nginx'
    ports:
      - "80:80"  # Expose NGINX on port 80 of the host
    volumes:
      - .\src\nginx\nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-order
      - api-inventory
